import type { Metadata } from "next";
import { Inter, 
  // Montserrat 
} 
  from "next/font/google";
// import { Agbalumo } from "next/font/google";
import "./globals.css";
import WhatsAppButton from "@/components/WhatsAppButton";
import Header from "@/components/Header";


// const agbalumo = Agbalumo({
//   weight: ["400"],
//   subsets: ["latin"],
// });

const inter = Inter({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

// const montserrat = Montserrat({
//   weight: ["400", "500", "600", "700"],
//   subsets: ["latin"],
// });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning className={`${inter.className} font-sntialiased`}
      >
        <main>
          <Header />
          {children}
          <WhatsAppButton />
        </main>
      </body>
    </html>
  );
}
